# Generated by Django 5.1.1 on 2024-09-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cities_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='Горящий тур'),
        ),
    ]
