# Generated by Django 5.1.1 on 2024-09-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tours_is_hot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='image',
            field=models.ImageField(upload_to='tours/', verbose_name='Изображение'),
        ),
    ]
