# Generated by Django 5.1.1 on 2024-09-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tours_special_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tours',
            name='special_offer',
        ),
        migrations.AddField(
            model_name='cities',
            name='image',
            field=models.ImageField(default=1, upload_to='cities/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cities',
            name='special_offer',
            field=models.BooleanField(default=False, verbose_name='Спецпредложение'),
        ),
    ]
