# Generated by Django 5.1.1 on 2024-09-26 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_tours_special_offer_cities_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('stars', models.IntegerField(verbose_name='Звезды')),
                ('image', models.ImageField(upload_to='hotels/', verbose_name='Изображение')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('review_points', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cities')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
    ]
